### ISSUE TITLE
Use consistent dbus path name.

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/phosphor-host-ipmid#102]
I mentioned in the code review https://gerrit.openbmc-project.xyz/#/c/1984/26/configure.ac@86 that we should discuss the appropriate name for this object path.  I believe we are suppose to have underscores here: soft_power_off.

          [SOFTOFF_OBJPATH="/xyz/openbmc_project/ipmi/internal/softpoweroff"])

**Comment by vishwabmc** [comment]
https://gerrit.openbmc-project.xyz/#/c/3428/
