### ISSUE TITLE
IPMI out-of-band "user list/summary" command fails without channel number

### ISSUE THREAD

**Issue by rahulmah** [openbmc/phosphor-host-ipmid#132]
With recent master, IPMI out-of-band "user list" command is failing without channel number. If we try the same with channel number, it works fine.  

Same is also seen with "user summary" command. Both use to work with older builds without channel number.

******************************
Without Channel number:

``` 
bash-4.1$ ipmitool -I lanplus -H <BMC_IP> -U root -P 0penBmc  user list
IPMI command failed: Invalid data field in request
bash-4.1$ ipmitool -I lanplus -H <BMC_IP> -U root -P 0penBmc  user summary
IPMI command failed: Invalid data field in request
 ```
 
******************************
With Channel number:

```
bash-4.1$ ipmitool -I lanplus -H <BMC_IP> -U root -P 0penBmc  user list 1
ID  Name             Callin  Link Auth  IPMI Msg   Channel Priv Limit
1   root             false   true       true       ADMINISTRATOR
2                    true    false      false      NO ACCESS
3                    true    false      false      NO ACCESS
4                    true    false      false      NO ACCESS
5                    true    false      false      NO ACCESS
6                    true    false      false      NO ACCESS
7                    true    false      false      NO ACCESS
8                    true    false      false      NO ACCESS
9                    true    false      false      NO ACCESS
10                   true    false      false      NO ACCESS
11                   true    false      false      NO ACCESS
12                   true    false      false      NO ACCESS
13                   true    false      false      NO ACCESS
14                   true    false      false      NO ACCESS
15                   true    false      false      NO ACCESS
bash-4.1$ ipmitool -I lanplus -H <BMC_IP> -U root -P 0penBmc  user summary 1
Maximum IDs         : 15
Enabled User Count  : 1
Fixed Name Count    : 0
bash-4.1$
```

OpenBMC build info:
```
root@witherspoon:~# cat /etc/os-release
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="2.7.0-dev"
VERSION_ID="2.7.0-dev-222-g4b8d2d036"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) 2.7.0-dev"
BUILD_ID="2.7.0-dev"
OPENBMC_TARGET_MACHINE="witherspoon"
root@witherspoon:~#
```

**Comment by rthomaiy** [comment]
Issue is due to the recent change in the ipmi architecture whereas all the commands are executed by host-ipmid daemon itself (vernon already provided context behavior in his new handlers, and user commands has to be ported to this so that it can get the context which will be able to identify the channel number it is coming in). Will work on changes for the same.

**Comment by rthomaiy** [comment]
@rthomaiy adding myself for tracking purpose

**Comment by GoingOffRoading** [comment]
> Issue is due to the recent change in the ipmi architecture whereas all the commands are executed by host-ipmid daemon itself (vernon already provided context behavior in his new handlers, and user commands has to be ported to this so that it can get the context which will be able to identify the channel number it is coming in). Will work on changes for the same.

Was this changed made?

Having the same "Invalid data field in request" issue

**Comment by rthomaiy** [comment]
This is expected behavior. i.e. Internall ipmitool will send out the channel number based on the channel in which it is queried from
i.e. When queried using RMCP+, it will be assumed as LAN Channel number, and will list user list properly as expected. 
When the same is issued using KCS channel, then user list / authentication details are not available for KCS channel, and hence will return the error. 

This is working as expected.

**Comment by rahulmah** [comment]
@rthomaiy : This problem was seen with out-of-band IPMI. But anyways, I am not seeing this issue with latest master. So closing it.
