### ISSUE TITLE
Capabilities spelling needs to be corrected in dcmi discover output

### ISSUE THREAD

**Issue by rahulmah** [openbmc/phosphor-host-ipmid#140]
Capabilities spelling  need to be corrected in dcmi discover output.
It displays "capabilties" instead of "capabilities"

```ipmitool -I lanplus -C 3 -U root -P 0penBmc -H <BMC_IP> dcmi discover
    Supported DCMI capabilities:

         Mandatory platform capabilties

         Optional platform capabilties
        Power management available

         Managebility access capabilties
        In-band KCS channel available```

**Comment by mdmillerii** [comment]
@rahulmah please give the exact test command and tool version (is this automation tooling?)
I'd expect this to be your tooling as most ipmi is binary encoded values (assuming this is not a logging entry).

**Comment by bjwyman** [comment]
"This repository has been archived by the owner. It is now read-only."
https://github.com/openbmc/ipmitool/blob/dfdfd89ec9b36c115a98f589880fd757a162af19/lib/ipmi_dcmi.c#L121
https://github.com/openbmc/ipmitool/blob/dfdfd89ec9b36c115a98f589880fd757a162af19/lib/ipmi_dcmi.c#L849

https://sourceforge.net/projects/ipmitool/

The project has moved to GitHub at https://github.com/ipmitool/ipmitool

Looks like George Keishing fixed those typos and got them upstream:
https://github.com/ipmitool/ipmitool/commit/48f4fba39a70fbc2055feaeed500cd27174c0724
https://github.com/ipmitool/ipmitool/commit/48f4fba39a70fbc2055feaeed500cd27174c0724
