### ISSUE TITLE
IPMI and Redfish Showing different values of the same sensor at the same time.

### ISSUE THREAD

**Issue by cvam0000** [openbmc/phosphor-host-ipmid#192]
IPMI and Redfish Show different values of the same sensor at the same time.

```
ipmitool sensor list
 
FAN_1_F          | **12250.000**  | RPM        | ok    | na        | 2156.000  | na        | na        | na        | na     
```

```

      "@odata.id": "/redfish/v1/Chassis/BMC_0/Thermal#/Fans/0",
      "@odata.type": "#Thermal.v1_7_1.Fan",
      "LowerThresholdCritical": 2204,
      "MaxReadingRange": 25000,
      "MemberId": "FAN_1_F",
      "MinReadingRange": 0,
      "Name": "FAN 1 F",
      "Reading": **12288**,
      "ReadingUnits": "RPM",
      "Status": {
        "Health": "OK",
        "State": "Enabled"

```
There is a slight difference in both readings.

in IPMI is coming after converting from the conversion formula below.
![image](https://github.com/openbmc/phosphor-host-ipmid/assets/25868955/6a4f2ecb-1aa9-4030-aff8-f19daca966d0)

is this planned that way or do I have something wrong in my setup ?

**Comment by williamspatrick** [comment]
This is simply an artifact of the interpolation required by IPMI when converting to an integer-based representation.  Redfish shows a full precision number, while IPMI ends up with rounding.

**Comment by cvam0000** [comment]
@williamspatrick Is it healthy to set IPMI to not round up the values?

**Comment by williamspatrick** [comment]
> @williamspatrick Is it healthy to set IPMI to not round up the values?

Are you asking if it is reasonable to change the code to always round down?  Or are you asking if we can eliminate the rounding?

IPMI only allows 256 different values. There has to be rounding. 

You could potentially change the code so that the interpolation always goes to a smaller number, but I’m not sure if that is necessarily better or worse for all sensors. You’re welcome to submit code and see what the reviewers think.

**Comment by cvam0000** [comment]
I believe the sensor value in IPMI and Redfish should be identical. If we opt to maintain rounding off in IPMI, the same rounding off should be applied in Redfish. I am willing to contribute to this effort.

**Comment by williamspatrick** [comment]
It isn't a "rounding function" in IPMI.  The IPMI protocol only allows an 8-bit value for a sensor.  There is only so much data you can fit into an 8-bit value.

The function you copied in the picture at the very beginning is how IPMI fits more than 0-255 into an 8-bit value.  They use scaling to express a longer range.  The side effect of that is that you cannot represent all floating point values; you can only have `ipmitool` show you 256 different floating point values.  As a result, any sensor reading in between these interpolated values has to be "rounded".
