### ISSUE TITLE
ipmitool fru edit cmd returning sucess  while having an exception 

### ISSUE THREAD

**Issue by cvam0000** [openbmc/phosphor-host-ipmid#193]
```
root@bmc:~# ipmitool fru edit 215 field b 2 1111111111122
Updating Field '1111111111111' with '1111111111122' ...

root@bmc:~# ipmitool fru print 215
 Board Mfg Date        : xxx
 Board Mfg                 :  cvam
 Board Product          : xxx
 Board Serial             : 1111111111111
 Board Part Number     : 111-1cvam-0000-CV0
 Board Area Checksum   : OK
 Product Manufacturer  : cvam
 Product Name          : xxx
 Product Part Number   : xxxx-xxxx-xxxx-xxx
 Product Version       :  xxx
 Product Serial        : xxx
 Product Area Checksum : OK
```
journal 
```
ipmid[443]: error writing fru
```

I think instead of "Updating Field '1111111111111' with '1111111111122' ..." we should return an error here ?

https://github.com/openbmc/phosphor-host-ipmid/blob/f020c444e7c95fe9ae12cbf83a152d80ab1d754c/dbus-sdr/storagecommands.cpp#L151

**Comment by williamspatrick** [comment]
Shouldn’t it already be doing so?

https://github.com/openbmc/phosphor-host-ipmid/blob/f020c444e7c95fe9ae12cbf83a152d80ab1d754c/dbus-sdr/storagecommands.cpp#L521

**Comment by williamspatrick** [comment]
The code I referenced should be sending a failure completion code back to `ipmitool`.  Is it not?  What was the resulting rc?

If you want to change the behavior of ipmitool, you'll need to contribute that up to them.

https://codeberg.org/IPMITool/ipmitool

**Comment by williamspatrick** [comment]
My reading of the ipmitool code suggests that it should have printed out a message if the update failed.  So either I'm misreading ipmitool or the storagecommands.cpp link I gave above didn't give a failure rc.  Can you run a `busctl monitor` while you run this ipmi command to see what the completion code was?

**Comment by cvam0000** [comment]
yes here it is coming from https://codeberg.org/IPMITool/ipmitool/src/commit/81b8242768588f6e4eddb78fcf4099e191d8140e/lib/ipmi_fru.c#L4979

**Comment by williamspatrick** [comment]
Please take this up with the upstream tool.

**Comment by cvam0000** [comment]
sure ill ask ipmitool about this
