### ISSUE TITLE
Use libc inet_pton()/inet_ntop() to change IP address representations

### ISSUE THREAD

**Issue by amboar** [openbmc/phosphor-host-ipmid#65]
#64 pulls in custom code to parse numbers-and-dots IP addresses to 32bit binary values. libc provides functions like [inet_pton()](http://man7.org/linux/man-pages/man3/inet_pton.3.html) and [inet_ntop()](http://man7.org/linux/man-pages/man3/inet_ntop.3.html) to translate between representations; these should be used instead.

**Comment by tomjoseph83** [comment]
I did the changes using this pull request https://github.com/openbmc/phosphor-host-ipmid/pull/71

**Comment by vishwabmc** [comment]
Andrew,
Per above comment by Tom, can this be closed if you are okay with the changes ?. Is there anything else that needs to be done here ?

**Comment by amboar** [comment]
@vishwabmc The patch does eliminate the custom code, so this issue can be closed. The way the patch goes about it doesn't fill me with joy, but it's already merged so the how is a bit irrelevant.
