### ISSUE TITLE
Memory leaks in phosphor-host-ipmid

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/phosphor-host-ipmid#68]
There are a few sd_bus_message objects leaked:
* ipmi_app_get_device_guid - 'reply' is not unref'd.
* ipmi_app_set_watchdog - 'reply' is not unref'd twice.
* ipmi_app_reset_watchdog - 'reply' is not unref'd.
* ipmi_transport_set_lan - 'reply' is not unref'd, 'm' is not unref'd, and 'req'/'res' are not unref'd in at least one code path.
* ipmi_transport_get_lan - 'reply' and 'm' are not unref'd.

**Comment by vishwabmc** [comment]
I fixed the good path leaks in https://github.com/openbmc/phosphor-host-ipmid/pull/69

Looking at the code, there are leaks that are in bad path. IMO, these should need to get caught in code review. We would need to focus more on code reviews.

**Comment by vishwabmc** [comment]
Patrick, both the error and good paths leaks were fixed as part of  #69.
Can we close this issue now ?

**Comment by vishwabmc** [comment]
Since these paths are fixed using RTC: 148063, this can be closed. I do not have access to close it,

**Comment by anoo1** [comment]
Closing per above comments.
