### ISSUE TITLE
C++ code mixed throughout

### ISSUE THREAD

**Issue by KennethWilke** [openbmc/phosphor-host-ipmid#72]
I know this is probably just me nit-picking, but there's a few bits of C++ code scattered throughout this repo, in .c files. Can the cpp files be changed to a .cpp extension to reflect this more clearly? There are some namespaces and C++ headers used here and there.

**Comment by jk-ozlabs** [comment]
Ack, and this fix would mean we can probably simplify our makefiles too.

**Comment by jk-ozlabs** [comment]
Actually, it looks like the C++ files are .C (not .c), which is fairly standard. Or are there ones I'm missing here?

**Comment by KennethWilke** [comment]
Ahh, my apologies! I haven't worked with c++ that used that extension and wasn't familiar with that convention.
