### ISSUE TITLE
handle errors finding openbmc_path

### ISSUE THREAD

**Issue by vishwabmc** [openbmc/phosphor-host-ipmid#75]
These code paths in  ipmid.C needs to handle the error on resolving the openbmc path.

int set_sensor_dbus_state_s(uint8_t number, const char *method, const char *value) {

    r = find_openbmc_path("SENSOR", number, &a);

    << Error handling needs to go here >>

    r = sd_bus_message_new_method_call(bus,&m,a.bus,a.path,a.interface,method);
    if (r < 0) {
------------
int set_sensor_dbus_state_y(uint8_t number, const char *method, const uint8_t value) {
   r = find_openbmc_path("SENSOR", number, &a);

   << Error handling needs to go here >>

    r = sd_bus_message_new_method_call(bus,&m,a.bus,a.path,a.interface,method);
    if (r < 0) {
----------------------

File : Storageaddsec.C

int create_esel_association(const uint8_t *buffer, char **m) {

    find_openbmc_path("SENSOR", sensor, &dbusint);

   << Do we need to check if r || this strlen  ?? >>

    // Simply no associations if the sensor can not be found
    if (strlen(dbusint.path) < 1) {

----------------

sensorhandler.C
-----

ipmi_ret_t ipmi_sen_get_sensor_reading(ipmi_netfn_t netfn, ipmi_cmd_t cmd,
    r = find_openbmc_path("SENSOR", reqptr->sennum, &a);
    << Validation needs to go here >>
    type = find_sensor(reqptr->sennum);

**Comment by williamli80** [comment]
I'd like to finish this.

**Comment by williamli80** [comment]
PR :  https://github.com/openbmc/phosphor-host-ipmid/pull/86
