### ISSUE TITLE
Cleanup needed in storageaddsel.C

### ISSUE THREAD

**Issue by vishwabmc** [openbmc/phosphor-host-ipmid#76]
1: send_esel_to_dbus returns an integer value but its not consumed by send_esel.

2: In getfilestream API, need to handle errors during file IO. Currently, it assumes everything will go right.

**Comment by williamli80** [comment]
HI, I'd like to work on this one.

**Comment by williamli80** [comment]
Hi, PR : https://github.com/openbmc/phosphor-host-ipmid/pull/87

**Comment by anoo1** [comment]
hi @vishwabmc , please review the PR addresses the concerns of this issue.
