### ISSUE TITLE
Returning correct value from handle_ipmi_command in ipmid.C

### ISSUE THREAD

**Issue by vishwabmc** [openbmc/phosphor-host-ipmid#77]
Currently, ipmid.C code has :

    // Now that we have parsed the entire byte array from the caller
    // we can call the ipmi router to do the work...
    r = ipmi_netfn_router(netfn, cmd, (void *)request, (void *)response, &resplen);
    if(r != 0)
    {
        fprintf(stderr,"ERROR:[0x%X] handling NetFn:[0x%X], Cmd:[0x%X]\n",r, netfn, cmd);
    }
   
Since "return -1" has been heavily used inside the plugin code that handles the commands, we need to re map that to something appropriate that is per IPMI spec.

This is what I was suggesting :
    r = ipmi_netfn_router(netfn, cmd, (void *)request, (void *)response, &resplen);
    if(r != 0)
    {
        fprintf(stderr,"ERROR:[0x%X] handling NetFn:[0x%X], Cmd:[0x%X]\n",r, netfn, cmd);
    }
 +  if (r == -1)
 +  {
 +     r = IPMI_CC_INVALID;  ( Or anything more meaningful in  ipmid-api.h )
+  }
+   memcpy(response, &r, IPMI_CC_LEN);

**Comment by williamli80** [comment]
Hi, in ipmi spec 2.0, "IPMI_CC_INVALID"(C1h) is used to indicate an unrecognized or unsupported command.  After deep into our code, I find we  usually do "return -1" when failing to call sd-bus method. So I think maybe "Cannot execute command"(D5h) is more suitable, which indicates commands, or request parameter(s), not supported in present state.  Please correct me.

**Comment by vishwabmc** [comment]
hello Nan,

I do not feel that we need a OEM command to do this.
0xFF, 255, "Unspecified error" may make more sense than D5h since D5h is about not supporting a requested parameter than about the internal failures. ( 0xD5, 213, "Cannot execute command. Request parameters not supported", ).

Please let me know your thoughts.. Thanks

**Comment by williamli80** [comment]
Thanks for your reply. Yes, "0xff" make more sense.

**Comment by williamli80** [comment]
Pull request: https://github.com/openbmc/phosphor-host-ipmid/pull/88
