### ISSUE TITLE
Re structure handle_ipmi_command function in ipmid.C

### ISSUE THREAD

**Issue by vishwabmc** [openbmc/phosphor-host-ipmid#78]
Currently, ipmitool hangs if it does not see a response packet for the IPMI message that was sent in that session. 

It does not understand the return code of just 'rc' and mandates that a response packet be sent. This can not be always guaranteed in these scenarios.

1/. There is an error reading the user message itself into netfn,cmd tuple
2/. There is an error reading the user input buffer that is part of the message
3/. There is an error sending the ipmi response itself.

So we need to figureout if the change needs to go into ipmid.C -or- something for ipmitool itself.

**Comment by vishwabmc** [comment]
To me, it looks like we may not want to make any changes to ipmid.C since the system problem that we are dealing with now is already in an error path so can not guarantee anything.

More appropriate would be to see if the sender can timeout on the response and print an error message than hanging.. However, if we need to timeout then we need to see what is the acceptable timeout per IPMI V2.0 spec.

Also, need to see if the btbridge is already timing out and handling this.

**Comment by vishwabmc** [comment]
Patrick and I talked and what I told him was that we may not want to make any change in the ipmitool -I dbus since its not going to be shipped and as long as the BTBRIDGE is handling the timeouts, then it is fine and he is OK with that.

I did some tests today where I put a sleep(90) in IPMID and then started btbridged --vv and saw these outputs.

Case : 1 --> GOOD case where IPMID responds to the messages appropriately.
----------------------------------------------------------------------------------------------------
[BTBRIDGED 1469175156.187508721] Sending dbus signal with seq 0x07, netfn 0x0a, lun 0x00, cmd 0x12
[BTBRIDGED 1469175156.187737617]        0x13 0x00 0x00 0x00 0x00 0x00 0x00 0x00 
[BTBRIDGED 1469175156.187948825]        0x00 0x00 0x00 
IPMI Incoming: Seq 0x07, NetFn 0x0a, CMD: 0x12 
0x000000: 13 00 00 00 00 00 00 00 00 00 00                ...........     
Invalid entry:[0] in byte-0
Failed to validate common header
IPMI Response:
0x000000: 00 08                                           ..              
[BTBRIDGED 1469175156.294197242] Received a dbus response for msg with seq 0x07
[BTBRIDGED 1469175156.294426055] Processed 1 dbus events
[BTBRIDGED 1469175156.294591513] Disabling timer, no elements remain in queue
[BTBRIDGED 1469175156.294740075] Successfully wrote 6 of 6 bytes to /dev/bt-host
[BTBRIDGED 1469175156.295098784] Turning off POLLOUT for the BT in poll()
[BTBRIDGED 1469175156.295246263] Completed request with seq 0x07, netfn 0x0b, lun 0x00, cmd 0x12, cc 0x00

==============================

Case-2 :  Having a sleep(90) in IPMI daemon code.
-------------------------------------------------------------------
[BTBRIDGED 1469172044.715446725] Sending dbus signal with seq 0x02, netfn 0x06, lun 0x00, cmd 0x06
[BTBRIDGED 1469172044.717567704]        0xa0 0x7f 
[BTBRIDGED 1469172045.715387267] Timeout on msg with seq: 0x02
[BTBRIDGED 1469172045.717755600] Disabling timer, no elements remain in queue
[BTBRIDGED 1469172045.720072184] Successfully wrote 5 of 5 bytes to /dev/bt-host
[BTBRIDGED 1469172045.722936975] Turning off POLLOUT for the BT in poll()
[BTBRIDGED 1469172045.724994100] Completed request with seq 0x02, netfn 0x07, lun 0x00, cmd 0x06, cc 0xce
[BTBRIDGED 1469172045.727474559] No message found to send timeout
[BTBRIDGED 1469172045.729287205] Sending dbus signal with seq 0x03, netfn 0x06, lun 0x00, cmd 0x24
[BTBRIDGED 1469172045.731433705]        0x41 0x01 0x00 0x02 0xb0 0x04 
[BTBRIDGED 1469172046.735360413] Timeout on msg with seq: 0x03
[BTBRIDGED 1469172046.737729267] Disabling timer, no elements remain in queue
[BTBRIDGED 1469172046.740060392] Successfully wrote 5 of 5 bytes to /dev/bt-host
[BTBRIDGED 1469172046.742386538] Turning off POLLOUT for the BT in poll()
[BTBRIDGED 1469172046.744441496] Completed request with seq 0x03, netfn 0x07, lun 0x00, cmd 0x24, cc 0xce
[BTBRIDGED 1469172046.746023517] No message found to send timeout
[BTBRIDGED 1469172046.764839538] Sending dbus signal with seq 0x04, netfn 0x06, lun 0x00, cmd 0x22
[BTBRIDGED 1469172047.765358059] Timeout on msg with seq: 0x04
[BTBRIDGED 1469172047.767709976] Disabling timer, no elements remain in queue
[BTBRIDGED 1469172047.770037142] Successfully wrote 5 of 5 bytes to /dev/bt-host
[BTBRIDGED 1469172047.772467267] Turning off POLLOUT for the BT in poll()
[BTBRIDGED 1469172047.774969642] Completed request with seq 0x04, netfn 0x07, lun 0x00, cmd 0x22, cc 0xce

=========================

As we can see, BTBRIDGE has a timeout of "1 second" for the IPMI Netfn/Cmd. 

#define BT_HOST_TIMEOUT_SEC 1
..
     /* Set expiry */
        head->expired = 1;
        head->rsp.seq = head->req.seq;
....


In the code, it has a dispatch_timer that sets the timerfd to 1 second for the IPMI NetFn/Cmd.

=================================================

So I conclude that we do not need any change to any code here since the timeous is already handled in the BTBRIDGE.

@williamspatrick @cyrilbur-ibm Please let me know if you have any comments .

**Comment by vishwabmc** [comment]
This can be closed too since no change needed here.

**Comment by williamspatrick** [comment]
I thought we discussed doing a change to the btbridge sequence ID?  Have you created an issue for that?

**Comment by vishwabmc** [comment]
@williamspatrick yes.. The reason why I closed this one is because it has the solution for the problem stated in this issue.. 

yeah, I have drafted that and will paste that into github issue and update the number here.

**Comment by vishwabmc** [comment]
Opened https://github.com/openbmc/openbmc/issues/494 for handling timeouts in a better way.

**Comment by williamspatrick** [comment]
openbmc/openbmc#494
