### ISSUE TITLE
Fails to compile

### ISSUE THREAD

**Issue by shenki** [openbmc/phosphor-host-ipmid#99]
With b898314b84e808d8e64c759140bdead2e573e78e:

```
joel@aurora ~/dev/obmc/phosphor-host-ipmid :master 
$ ./bootstrap.sh 
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
libtoolize: and rerunning libtoolize and aclocal.
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
configure.ac:26: error: possibly undefined macro: LT_LIB_DLLOAD
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
Run "./configure ${CONFIGURE_FLAGS} && make"
joel@aurora ~/dev/obmc/phosphor-host-ipmid :master 
$ ./configure 
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."
```

If I run `bootstrap.sh` a second time:

```
joel@aurora ~/dev/obmc/phosphor-host-ipmid :master 
$ ./bootstrap.sh 
libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
libtoolize: and rerunning libtoolize and aclocal.
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
configure.ac:11: installing './ar-lib'
configure.ac:10: installing './compile'
configure.ac:25: installing './config.guess'
configure.ac:25: installing './config.sub'
configure.ac:5: installing './install-sh'
configure.ac:5: installing './missing'
Makefile.am: installing './depcomp'
Run "./configure ${CONFIGURE_FLAGS} && make"
joel@aurora ~/dev/obmc/phosphor-host-ipmid :master 
$ ./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
./configure: line 3690: syntax error near unexpected token `noext'
./configure: line 3690: `AX_CXX_COMPILE_STDCXX_14(noext)'
```

**Comment by williamspatrick** [comment]
The instructions are written somewhat assuming you are building within an SDK, which maybe isn't ideal. If you are not running in the SDK you need to have autoconf-archive installed.

**Comment by msbarth** [comment]
I am not able to reproduce any of the issue show here from within an SDK. Please re-attempt after rebasing from within an SDK.

**Comment by shenki** [comment]
As I have said in the past, I recommend we make all of our tools able to compile outside of the bitbake SDK. This allows at the very least compile testing and static analysis to be run on a desktop Linux distribution.

**Comment by williamspatrick** [comment]
As I mentioned before, you need to have autoconf-archive installed.  I did a fresh download of this repository and have no problem getting past configure.

There are two issues to be addressed:
    1. We need to find a place to document the need for autoconf-archive to be installed.
    2. The AC_CHECK_LIB([mapper], [mapper_get_service]) does not appear to work.  I do not have mapper installed and yet I am passing ./configure (and then later failing in make due to missing header file).  We should also enhance this to check for the header file for mapper.

```
checking for mapper_get_service in -lmapper... no  <---- why doesn't this halt?
```

```
  CXX      libapphandler_la-apphandler.lo
apphandler.cpp:8:20: fatal error: mapper.h: No such file or directory
compilation terminated.
Makefile:747: recipe for target 'libapphandler_la-apphandler.lo' failed
```

**Comment by stewart-ibm** [comment]
You can also store copies of needed autoconf macros in m4/ (or whatever directory you configure) and it'll work even if you don't have autoconf-archive installed. I can't remember what precedence it all is though :)

**Comment by msbarth** [comment]
Issue #100 was created to address halting the ./configure step where libmapper is not found.

This issue will track adding the use of "m4-ifndef" checks for none autoconf default macros (i.e. autoconf-archive macros, etc..) prior to use.

**Comment by williamspatrick** [comment]
I think this has been solved at this point.
